config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :charges
  devise_for :users,
    controllers: { sessions: 'users/sessions' },
    path_names: { sign_in: 'login', sign_out: 'logout' }

  root 'servers#index'
  resources :servers do
    member do
      get :monitor
      get :router
      # get :config
      get :expiry_date
      post :restart_delayed_job
      post :restart_puma
      post 'delayed_job/:status', to: 'servers#delayed_job', as: :delayed_job
      post :expiry_date
      post 'deploy/:app', to: 'servers#deploy', as: :deploy
    end
    collection do
      get :cloud_server
      get :reset_all_paid
      post :import 
    end
  end
  
  resources :conversations, only: [:create]

  get 'dashboard_page/front_page'
  get 'conversations/index'
  get 'maintener_guides/index'

  resources :servers
  resources :engineers
end

app/views/shared/_alert.html.slim
- if notice
  .alert.alert-info.alert-dismissible
    button.close data-dismiss="alert" aria-hidden="true" ×
    = notice
- if alert
  .alert.alert-danger.alert-dismissible
    button.close data-dismiss="alert" aria-hidden="true" ×
    = alert

app/views/shared/_control_sidebar.html.slim
/! Control Sidebar
aside.control-sidebar.control-sidebar-dark
  /! Create the tabs
  ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
    li.active
      a data-toggle="tab" href="#control-sidebar-home-tab"
        i.fa.fa-home
    li
      a data-toggle="tab" href="#control-sidebar-settings-tab"
        i.fa.fa-gears
  /! Tab panes
  .tab-content
    /! Home tab content
    #control-sidebar-home-tab.tab-pane.active
      h3.control-sidebar-heading Recent Activity
      ul.control-sidebar-menu
        li
          a href="javascript:;"
            i.menu-icon.fa.fa-birthday-cake.bg-red
          .menu-info
            h4.control-sidebar-subheading Langdon's Birthday
            p Will be 23 on April 24th
      /! /.control-sidebar-menu
      h3.control-sidebar-heading Tasks Progress
      ul.control-sidebar-menu
        li
          a href="javascript:;"
          h4.control-sidebar-subheading
            | Custom Template Design
            span.pull-right-container
              span.label.label-danger.pull-right 70%
          .progress.progress-xxs
            .progress-bar.progress-bar-danger style=("width: 70%")
      /! /.control-sidebar-menu
    /! /.tab-pane
    /! Stats tab content
    #control-sidebar-stats-tab.tab-pane Stats Tab Content
    /! /.tab-pane
    /! Settings tab content
    #control-sidebar-settings-tab.tab-pane
      form method="post"
        h3.control-sidebar-heading General Settings
        .form-group
          label.control-sidebar-subheading
            | Report panel usage
            input.pull-right checked="" type="checkbox" /
          p
            | Some information about this general settings option
        /! /.form-group
    /! /.tab-pane
/! /.control-sidebar
/!
  | Add the sidebar's background. This div must be placed
  | immediately after the control sidebar
.control-sidebar-bg

app/views/shared/_footer.html.slim
footer.main-footer
  .pull-right.hidden-xs
    b Version&nbsp;
    | 1.0
  strong
    | Copyright &copy; 2018.&nbsp;
    a href="http://eresto.co.id" target="_blank" eResto
  | &nbsp;All rights reserved.

app/views/shared/_navbar.html.slim
nav.navbar.navbar-static-top role="navigation"
  a.sidebar-toggle data-toggle="push-menu" href="#" role="button"
    span.sr-only Toggle navigation

  .navbar-custom-menu
    ul.nav.navbar-nav
      li.dropdown.user.user-menu
        a.dropdown-toggle data-toggle="dropdown" href="#"
          = image_tag 'eresto-white.png', class: 'user-image'
          span.hidden-xs = current_user.name
        ul.dropdown-menu
          li.user-header
            = image_tag 'eresto-white.png', class: 'img-circle'
            p
              = current_user.name
              | &nbsp;- Server Admin
              small = "Member since #{current_user.member_since}"
          li.user-footer
            = button_to 'Logout', destroy_user_session_path, class: 'btn btn-default btn-flat btn-block', method: :delete

      / li
      /   a data-toggle="control-sidebar" href="#"
      /     i.fa.fa-gears

app/views/shared/_sidebar.html.slim
aside.main-sidebar
  section.sidebar
    .user-panel
      .pull-left.image
        = image_tag 'eresto.png', class: 'img-circle'
      .pull-left.info
        p eResto Admin
        a href="#"
          i.fa.fa-circle.text-success
          | Online

    ul.sidebar-menu data-widget="tree"
      li.header style='padding:0px;'
        a href='/dashboard_page/front_page'
            i.fa.fa-dashboard
            | &nbsp; Dashboard Main
        a href='/'
          - unless request.path.eql?('/')
            i.fa.fa-chevron-left
          - if in_server_page?
            = " #{@server.name}"
          - else
            | &nbsp;LOCAL SERVER
      li.header style='padding:0px;'
        a href='/servers/cloud_server'
          - unless request.path.eql?('/servers/cloud_server')
            i.fa.fa-chevron-left
          - if in_cloud_server_page?
            = " #{@server.name}"
          - else
            | &nbsp;CLOUD SERVER
      - if in_server_page?
        //li class=(active?('monitor'))
          //= link_to monitor_server_path(@server.id)
            //i.fa.fa-area-chart
            //span Monitor Server
        //li class=(active?('router'))
          //= link_to router_server_path(@server.id), target: '_blank'
            //i.fa.fa-signal
            //span Access Router
        //li class=(active?('config'))
          //= link_to config_server_path(@server.id)
            //i.fa.fa-cog
            //span Config Server
        li class=(active?('edit'))
          = link_to edit_server_path(@server.id)
            i.fa.fa-edit
            span Edit Server
      li class=(active?('engineer'))
        - if current_user.role == 'admin'
          = link_to engineers_path
            i.fa.fa-users
            span Network Engineer
        = link_to conversations_index_path
            i.fa.fa-comments-o
            span Conversations
        = link_to maintener_guides_index_path
            i.fa.fa-graduation-cap
            span Maintener Guides
        - if current_user.role == 'admin'
          = link_to charges_path
              i.fa.fa-money 
              span Charges