config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :charges
  devise_for :users,
    controllers: { sessions: 'users/sessions' },
    path_names: { sign_in: 'login', sign_out: 'logout' }

  root 'servers#index'
  resources :servers do
    member do
      get :monitor
      get :router
      # get :config
      get :expiry_date
      post :restart_delayed_job
      post :restart_puma
      post 'delayed_job/:status', to: 'servers#delayed_job', as: :delayed_job
      post :expiry_date
      post 'deploy/:app', to: 'servers#deploy', as: :deploy
    end
    collection do
      get :cloud_server
      get :reset_all_paid
      post :import 
    end
  end
  
  resources :conversations, only: [:create]

  get 'dashboard_page/front_page'
  get 'conversations/index'
  get 'maintener_guides/index'

  resources :servers
  resources :engineers
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :authenticate_user!
  before_action :only_admin!
  before_action :set_engineer, except: [:index, :new, :create]

  def index
    @engineers = User.where.not(id: current_user.id).pluck(:id, :user_avatar, :name, :role)
  end

  def new
    @engineer = User.new
  end

  def create
    @engineer = User.new(engineer_params)

    if @engineer.save
      redirect_to engineers_url, notice: 'New engineer created!'
    else
      render :new
    end
  end

  def update
    if update_engineer
      redirect_to engineers_url, notice: 'Engineer data updated!'
    else
      render :edit
    end
  end

  def destroy
    @engineer.destroy
    redirect_to engineers_url, notice: 'Engineer data deleted!'
  end

  private
    def set_engineer
      @engineer = User.find(params[:id])
    end

    def engineer_params
      params.require(:user).permit(:email, :password, :name, :user_avatar).merge(role: 1)
    end

    def update_engineer
      if engineer_params[:password].blank?
        params[:user].delete('password')
        @engineer.update_without_password(engineer_params)
      else
        @engineer.update(engineer_params)
      end
    end

    def only_admin!
      unless current_user.admin?
        redirect_to root_url, alert: 'You dont have access to this page'
      end
    end
end

app/views/engineers/_form.html.slim
= simple_form_for(@engineer, url: url) do |f|
  = f.error_notification
  .box-body
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :user_avatar

  .box-footer
    button.btn.btn-primary type="submit" data-disable-with='Please wait...' Submit

app/views/engineers/edit.html.slim
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        h3.box-title Edit Engineer

      = render 'form', url: engineer_path(@engineer), engineer: @engineer

app/views/engineers/index.html.slim
section.content-header
  h1 Network Engineers
section.content.container-fluid
  .row
    .col-md-12
      .box.box-info
        .box-header.with-border
          h2.box-title Engineers
          .box-tools.pull-right
            button.btn.btn-box-tool data-widget="collapse" type="button"
              i.fa.fa-minus
            / button.btn.btn-box-tool data-widget="remove" type="button"
              i.fa.fa-times

        .box-body
          .table-responsive
            table#engineer-list.table.no-margin.table.table-bordered.table-striped
              thead
                tr
                  th Engineer ID
                  th Engineer Avatar
                  th Name
                  th Role
                  th Action
              tbody
                - @engineers.each do |engineer|
                  tr
                    td = "NG#{engineer[0]}"
                    td = image_tag engineer[1], height: '80', width: '80', class:'img-circle' unless engineer[1].blank?
                    td = engineer[2]
                    td = engineer[3].titleize
                    td
                      = link_to edit_engineer_path(engineer[0]), class: 'btn btn-success btn-sm btn-flat'
                        i.fa.fa-cog
                        | &nbsp;Edit
                      | &nbsp;
                      = button_to engineer_path(engineer[0]), class: 'btn btn-danger btn-sm btn-flat', data: {confirm: 'Are you sure?'}, method: :delete, title: 'Remove'
                        i.fa.fa-trash

        .box-footer.clearfix
          = link_to 'New Engineer', new_engineer_path, class: 'btn btn-sm btn-info btn-flat pull-left'

app/views/engineers/new.html.slim
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        h3.box-title New Engineer

      = render 'form', url: engineers_path, engineer: @engineer