config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :charges
  devise_for :users,
    controllers: { sessions: 'users/sessions' },
    path_names: { sign_in: 'login', sign_out: 'logout' }

  root 'servers#index'
  resources :servers do
    member do
      get :monitor
      get :router
      # get :config
      get :expiry_date
      post :restart_delayed_job
      post :restart_puma
      post 'delayed_job/:status', to: 'servers#delayed_job', as: :delayed_job
      post :expiry_date
      post 'deploy/:app', to: 'servers#deploy', as: :deploy
    end
    collection do
      get :cloud_server
      get :reset_all_paid
      post :import 
    end
  end
  
  resources :conversations, only: [:create]

  get 'dashboard_page/front_page'
  get 'conversations/index'
  get 'maintener_guides/index'

  resources :servers
  resources :engineers
end

app/models/charge.rb
# == Schema Information
#
# Table name: charges
#
#  id           :integer          not null, primary key
#  amount       :integer
#  payment_desc :string
#  status       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  server_id    :integer
#
# Indexes
#
#  index_charges_on_server_id  (server_id)
#
class Charge < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  belongs_to :server
  enum status: { cash: 0, transfer: 1 }

  def receipt
    Receipts::Invoice.new(
      details: [
        ["Receipt Number", "CH-00#{id}"],
        ["Date paid", Date.today],
        ["Payment Type", "<b><color rgb='#5eba7d'>#{status}</color></b>"]
        ],
        company: {
          name: "PT.Eresto Digital Indonesia",
          address: "Komp.Kota Kembang Permai\n kav 1 No.20-22\nBandung, 40271",
          email: "support@eresto.co.id",
          logo: File.expand_path("./app/assets/images/eresto.png")
        },
        recipient: [
          "<b>#{server.name}</b>",
        ],
        line_items: [
          ["<b>Item</b>", "<b>Unit Cost</b>", "<b>Quantity</b>", "<b>Amount</b>"],
          ["Maintenance", "#{total_in_currency}", "1", "#{total_in_currency}"],
          [nil, nil, "Subtotal", "#{total_in_currency}"],
          [nil, nil, "Tax", "Rp.0"],
          [nil, nil, "Total", "#{total_in_currency}"],
          [nil, nil, "<b>Amount paid</b>", "<b>#{total_in_currency}</b>"],
          # [nil, nil, "Refunded on #{Date.today}", "$5.00"]
        ],
        footer: "For questions, contact us anytime at <b>support@eresto.co.id</b>"
      )
  end

  def total_in_currency
    number_to_currency(amount, unit: 'Rp', precision: 2)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  def index
    @charges = Charge.all
    @total_charge = @charges.sum { |charge| charge.amount }
  end

  # GET /charges/1
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf { send_pdf }
    end
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  def create
    @charge = Charge.new(charge_params)

    if @charge.save
      redirect_to charges_url, notice: 'Charge was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /charges/1
  def update
    if @charge.update(charge_params)
      redirect_to charges_url, notice: 'Charge was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /charges/1
  def destroy
    @charge.destroy
    redirect_to charges_url, notice: 'Charge was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    def send_pdf
      send_data @charge.receipt.render,
        filename: "#{@charge.created_at.strftime("%Y-%m-%d")}-gorails-receipt.pdf",
        type: "application/pdf",
        disposition: :inline # or :attachment to download
    end

    # Only allow a trusted parameter "white list" through.
    def charge_params
      params.require(:charge).permit(:server_id, :payment_desc, :amount, :status)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.slim
= simple_form_for(@charge) do |f|
  = f.error_notification

  .form-inputs
    = f.association :server
    = f.input :payment_desc
    = f.input :amount
    = f.input :status, collection: Charge.statuses.keys

  .form-actions
    = f.button :submit

app/views/charges/edit.html.slim
h1 Editing charge

== render "form"

=> link_to "Show", @charge
'|
=< link_to "Back", charges_path

app/views/charges/index.html.slim
/ h1 Listing charges

/ table
/   thead
/     tr
/       th Server
/       th Payment desc
/       th Amount
/       th Payment type
/       th
/       th
/       th

/   tbody
/     - @charges.each do |charge|
/       tr
/         td = charge.server
/         td = charge.payment_desc
/         td = charge.amount
/         td = charge.payment_type
/         td = link_to "Show", charge
/         td = link_to "Edit", edit_charge_path(charge)
/         td = link_to "Destroy", charge, data: {confirm: "Are you sure?"}, method: :delete

/ br

/ = link_to "New Charge", new_charge_path
section.content-header
  h1 Charges
  .col-md-3.col-sm-6.col-xs-12.pull-right
    .info-box
      span.info-box-icon.bg-aqua
        i.fa.fa-usd
      .info-box-content
        span.info-box-text
          | Total Income
        span.info-box-number
          | 
          h4= number_to_currency(@total_charge, unit: "Rp", precision: 2)
section.content.container-fluid
  .row
    .col-md-12
      .box.box-info
        .box-header.with-border
          h2.box-title Charge Lists
          .box-tools.pull-right
            button.btn.btn-box-tool data-widget="collapse" type="button"
              i.fa.fa-minus
            / button.btn.btn-box-tool data-widget="remove" type="button"
              i.fa.fa-times

        .box-body
          .table-responsive
            table#engineer-list.table.no-margin.table.table-bordered.table-striped
              thead
                tr
                  th Charge ID
                  th Server Name
                  th Payment Description
                  th Amount
                  th Payment Type
                  th Action
              tbody
                - @charges.each do |charge|
                  tr
                    td = "CH-00#{charge.id}"
                    td = charge.server.try(:name)
                    td = charge.payment_desc
                    td = number_to_currency(charge.amount, unit: "Rp", precision: 2)
                    td = charge.status
                    td
                      = link_to edit_charge_path(charge.id), class: 'btn btn-success btn-sm btn-flat', data: { toggle: 'tooltip', placement: 'top', original_title: 'Edit Charge' }
                        i.fa.fa-cog
                        | &nbsp;Edit
                      | &nbsp;
                      = link_to charge_path(charge.id, format: :pdf), class: 'btn btn-info btn-sm btn-flat', target: "_blank", data: { toggle: 'tooltip', placement: 'top', original_title: 'View Invoice' }
                        i.fa.fa-file-pdf-o
                        | &nbsp;Invoice
                      /= button_to charge_path(charge[0]), class: 'btn btn-danger btn-sm btn-flat', data: {confirm: 'Are you sure?'}, method: :delete, title: 'Remove'
                        i.fa.fa-trash

        .box-footer.clearfix
          = link_to 'New Charge', new_charge_path, class: 'btn btn-sm btn-info btn-flat pull-left'
          / .pull-right
          /   strong 
          /     | 
          /     = number_to_currency(@total_charge, unit: "Rp", precision: 2)

app/views/charges/new.html.slim
h1 New charge

== render "form"

= link_to "Back", charges_path

app/views/charges/show.html.slim
p#notice = notice

p
  strong Server:
  = @charge.server.name

p
  strong Payment desc:
  = @charge.payment_desc

p
  strong Amount:
  = @charge.amount

p
  strong Payment type:
  = @charge.status

=> link_to "Edit", edit_charge_path(@charge)
'|
=< link_to "Back", charges_path
'|
=< link_to "View invoice", charge_path(@charge, format: :pdf)